export default {
  api: {
    results: 3,
    fixtures: [
      {
        fixture_id: 313307,
        league_id: 1063,
        league: {
          name: 'FA Cup',
          country: 'England',
          logo: null,
          flag: 'https://media.api-football.com/flags/gb.svg',
        },
        event_date: '2020-01-15T19:45:00+00:00',
        event_timestamp: 1579117500,
        firstHalfStart: 1579117500,
        secondHalfStart: 1579121100,
        round: '3rd Round Replays',
        status: 'Match Finished',
        statusShort: 'FT',
        elapsed: 90,
        venue: 'Old Trafford (Manchester)',
        referee: 'Kevin Friend, England',
        homeTeam: {
          team_id: 33,
          team_name: 'Manchester United',
          logo: 'https://media.api-football.com/teams/33.png',
        },
        awayTeam: {
          team_id: 39,
          team_name: 'Wolves',
          logo: 'https://media.api-football.com/teams/39.png',
        },
        goalsHomeTeam: 20,
        goalsAwayTeam: 0,
        score: {
          halftime: '0-0',
          fulltime: '1-0',
          extratime: null,
          penalty: null,
        },
      },
      {
        fixture_id: 157231,
        league_id: 524,
        league: {
          name: 'Premier League',
          country: 'England',
          logo: 'https://media.api-football.com/leagues/2.png',
          flag: 'https://media.api-football.com/flags/gb.svg',
        },
        event_date: '2020-01-11T15:00:00+00:00',
        event_timestamp: 1578754800,
        firstHalfStart: 1578754800,
        secondHalfStart: 1578758400,
        round: 'Regular Season - 22',
        status: 'Match Finished',
        statusShort: 'FT',
        elapsed: 90,
        venue: 'Old Trafford (Manchester)',
        referee: 'Anthony Taylor, England',
        homeTeam: {
          team_id: 33,
          team_name: 'Manchester United',
          logo: 'https://media.api-football.com/teams/33.png',
        },
        awayTeam: {
          team_id: 71,
          team_name: 'Norwich',
          logo: 'https://media.api-football.com/teams/71.png',
        },
        goalsHomeTeam: 4,
        goalsAwayTeam: 0,
        score: {
          halftime: '1-0',
          fulltime: '4-0',
          extratime: null,
          penalty: null,
        },
      },
      {
        fixture_id: 293220,
        league_id: 957,
        league: {
          name: 'League Cup',
          country: 'England',
          logo: null,
          flag: 'https://media.api-football.com/flags/gb.svg',
        },
        event_date: '2020-01-07T20:00:00+00:00',
        event_timestamp: 1578427200,
        firstHalfStart: 1578427200,
        secondHalfStart: 1578430800,
        round: 'Semi-finals',
        status: 'Match Finished',
        statusShort: 'FT',
        elapsed: 90,
        venue: 'Old Trafford, Manchester',
        referee: 'Mike Dean, England',
        homeTeam: {
          team_id: 33,
          team_name: 'Manchester United',
          logo: 'https://media.api-football.com/teams/33.png',
        },
        awayTeam: {
          team_id: 50,
          team_name: 'Manchester City',
          logo: 'https://media.api-football.com/teams/50.png',
        },
        goalsHomeTeam: 1,
        goalsAwayTeam: 3,
        score: {
          halftime: '0-3',
          fulltime: '1-3',
          extratime: null,
          penalty: null,
        },
      },
    ],
  },
};
