name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Build page
      with: # Set the secret as an input
        TEST1: ${{ secrets.TEST }}
        REACT_APP_TEST1: ${{ secrets.TEST }}
      env: # Or as an environment variable
        TEST2: ${{ secrets.TEST }}
        REACT_APP_TEST2: ${{ secrets.TEST }}
      run: REACT_APP_TEST3=${{ secrets.TEST }} npm run build
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./build